server:
  host: 0.0.0.0
  port: 8000

database:
  host: 127.0.0.1
  port: 3306
  user: hanif
  password: test
  dbname: garudacbt
  timezone: Asia/Makassar

secrets:
  jwtkey: helloworld

mode: development # production | development
